### ISSUE TITLE
端口号

### ISSUE THREAD

**Issue by viatovia** [ElemeFE/page-skeleton-webpack-plugin#1]
![image](https://user-images.githubusercontent.com/37997477/38187121-d6f661be-3688-11e8-87eb-ebbd73508127.png)
======
本地没有这个端口号的服务，排除端口号被占用的可能。

**Comment by Jocs** [comment]
是本地该端口号被占用了吗

**Comment by Jocs** [comment]
@viatovia 下一版本会提供 port 配置，这样就可以配置 PSWP 的服务端口号了。

**Comment by Jocs** [comment]
@viatovia 发布 v0.7.0 添加了 port 配置
