### ISSUE TITLE
webpack4 support and other features

### ISSUE THREAD

**Issue by yezongyang** [ElemeFE/page-skeleton-webpack-plugin#12]
1. webpack4 的插件写法有改动哈，webpack4不支持
2. 怎么实现multiple-page 骨架，路由配置好像只针对单页应用，能支持类似饿了么webapp这种多页面吗

**Comment by Jocs** [comment]
We are working on it now.

**Comment by Jocs** [comment]
>怎么实现multiple-page 骨架，路由配置好像只针对单页应用，能支持类似饿了么webapp这种多页面吗

我们的外卖移动端，是针对没有页面都有单独的打包，所以你可以在每个页面单独配置呢？

**Comment by Jocs** [comment]
@yezongyang 发布 0.10.12 版本，支持 webpack 4
