### ISSUE TITLE
千万不要使用这个项目，基本都是坑，也别浪费时间深入研究。

### ISSUE THREAD

**Issue by eavae** [ElemeFE/page-skeleton-webpack-plugin#133]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Plugin configration

for example:

```javascript
new SkeletonPlugin({
  pathname: path.resolve(__dirname, `./src`),
  port: '7890',
  loading: 'spin',
  svg: {
    color: '#EFEFEF',
    shape: 'circle',
    shapeOpposite: ['.red']
  },
  image: {
    shape: 'rect', // `rect` | `circle`
    color: '#EFEFEF',
    shapeOpposite: ['.white']
  },
  pseudo: {
    color: '#EFEFEF', // or transparent
    shape: 'circle', // circle | rect
    shapeOpposite: ['.apple', '.pen']
  },
  button: {
    color: '#EFEFEF',
    excludes: ['.center a']
  },
  defer: 5000,
  excludes: [],
  remove: [],
  hide: ['.ag-text', '.ag-image'],
  grayBlock: ['#header'],
  cssUnit: 'vw',
  cookies: [{
    name: 'SID',
    value: 'xxxxxx',
    url: 'https://xx.xxx.xx'
  }, {
    name: 'USERID',
    value: 'xxxxxx',
    url: 'https://xx.xxx.xx'
  }]
})
```

### Versions

- Page Skeleton:
- Webpack:

**Comment by whoopsHzh** [comment]
今天踩了好多坑，开不起来

**Comment by katoto** [comment]
+1 ，修改代码，生成的demo骨架屏没啥变化

**Comment by katoto** [comment]
写入到 shell.html 文件,这一步example 没有做到

**Comment by katoto** [comment]
还好，看了这个，遇到的坑，都解决了，https://juejin.im/post/5ed4c22ae51d4578810b5459

**Comment by katoto** [comment]
> +1 ，修改代码，生成的demo骨架屏没啥变化
还好，看了这个，遇到的坑，都解决了，https://juejin.im/post/5ed4c22ae51d4578810b5459
