### ISSUE TITLE
control+enter后报错

### ISSUE THREAD

**Issue by chenpengjun** [ElemeFE/page-skeleton-webpack-plugin#2]
`-> "[PSG] Evaluation failed: TypeError: Cannot read property 'length' of undefined
at forEach.type (:415:30)
at Array.forEach ()
at traverse (:414:27)
at genSkeleton (:518:5)
at :3:7"`

**Comment by Jocs** [comment]
这个 bug 会在下一个 npm release 修复，现在请参照 example 中 sale 例子配置，可以避免这个问题

**Comment by Jocs** [comment]
@chenpengjun 发布 v0.7.0 版本，这个问题修复了。
