### ISSUE TITLE
React使用该项目时，有一些问题

### ISSUE THREAD

**Issue by inier** [ElemeFE/page-skeleton-webpack-plugin#26]
React版本16+
React使用该项目时，有一些问题：
1. routes只能一个一个加入，添加多个，就无法生成骨架屏
2. 骨架页面预览没有界面显示，只有白屏，代码区也没有代码，也是空白

**Comment by sysuzero** [comment]
怎么解决

**Comment by baikaifa** [comment]
能看下你的react的demo么？我连项目都起不来，
