### ISSUE TITLE
运行sample中的sale没有生成骨架屏

### ISSUE THREAD

**Issue by seveny** [ElemeFE/page-skeleton-webpack-plugin#29]
运行sample中的sale没有生成骨架屏
![image](https://user-images.githubusercontent.com/953633/45205173-f7bc4100-b2b3-11e8-86fa-9f2b4fd92ac1.png)
![image](https://user-images.githubusercontent.com/953633/45205404-9a74bf80-b2b4-11e8-8a52-48d1947db01e.png)
![image](https://user-images.githubusercontent.com/953633/45205418-a5c7eb00-b2b4-11e8-9315-00cbbfb7cd2e.png)
终端并无报错，也无生成的信息，求指教

**Comment by FxPixels** [comment]
我也遇到这个情况，你怎么解决的

**Comment by Rudy24** [comment]
在开发页面中通过 Ctrl|Cmd + enter 呼出插件交互界面，或者在在浏览器的 JavaScript 控制台内输入toggleBar 呼出交互界面。

在浏览器控制台输入toggleBar 就可以生成预览页，我的是成功了，并没有报错
