### ISSUE TITLE
windows找不到chrome

### ISSUE THREAD

**Issue by linpenghui958** [ElemeFE/page-skeleton-webpack-plugin#3]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. 开始之后可以到generator HTML
![tim 20180409112836](https://user-images.githubusercontent.com/24564216/38478126-5adc058c-3be9-11e8-8986-3dda09a1b667.png)

但是接下来就会报错，并且弹出windows找不到chrome
![tim 20180409112046](https://user-images.githubusercontent.com/24564216/38478133-5e017512-3be9-11e8-8282-b592f55c3a4e.png)

chrome为最新版本
在同目录下，运行puppeteer的demo是可以唤出chrome
第一次配置skeleton，网上也搜不到相关的问题
如果有什么低级的错误，还请谅解

### Versions

- Page Skeleton: 0.7.0
- Webpack: 3.6.0

**Comment by Jocs** [comment]
@linpenghui958 能贴出来你的插件配置吗？

**Comment by linpenghui958** [comment]
![image](https://user-images.githubusercontent.com/24564216/38530349-8f0cd116-3c9c-11e8-89aa-f577ba625f18.png)
额。。我就写了再webpack.dev.conf里面添加了这一个plugin，其他都没加
例子里写的是${customPath}，直接照写会报这个undefined
所以我理解是不是写存放地址。
其他地方只有在index.html 里面添加了

**Comment by linpenghui958** [comment]
能看到打开的chrome，然后打开了当前页面，然后能看到生产的骨架屏一闪而过，然后就报错一样的windows找不到chrome就中止了
![screen](https://user-images.githubusercontent.com/24564216/38533172-a7f1dd80-3caa-11e8-838e-b23357042626.gif)

**Comment by Jocs** [comment]
@linpenghui958 也没有自动打开预览页面吗？

**Comment by Jocs** [comment]
@linpenghui958 可以加我微信号：ransixi 了解下是不是 windows 独有的 bug。

**Comment by coder-xiaotian** [comment]
@linpenghui958 请问这个问题解决了吗
