### ISSUE TITLE
page-skeleton-webpack-plugin安装失败!!!

### ISSUE THREAD

**Issue by yuanzhi0219** [ElemeFE/page-skeleton-webpack-plugin#30]
### Description

[yarn or npm 安装失败]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

error /Users/simon/Private/Vue/v-ym-mall/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/simon/Private/Vue/v-ym-mall/node_modules/puppeteer
Output:
ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: connect ETIMEDOUT 172.217.160.112:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.160.112',

### Versions

- Page Skeleton: 最新
- Webpack: 4.0以上

**Comment by ywyzxd** [comment]
@yuanzhi0219  以上问题怎么解决的呀？
