### ISSUE TITLE
examples/sale 示例没有骨架屏

### ISSUE THREAD

**Issue by doudounannan** [ElemeFE/page-skeleton-webpack-plugin#67]
### Description

examples/sale 示例没有骨架屏

### Steps to reproduce

```bash
$ npm run dev:sale
```

**Expected behavior:** 
示例应有骨架屏

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/6769584/50396210-89888500-07a3-11e9-8eb8-7c89b61c49be.png)

初始化 load 时并没有骨架屏显示。

**Link to an example:**
无

### Versions

- Page Skeleton: 0.10.12
- Webpack: 4.9.1

**Comment by doudounannan** [comment]
在开发页面中通过 Ctrl|Cmd + enter 呼出插件交互界面，或者在在浏览器的 JavaScript 控制台内输入toggleBar 呼出交互界面。

点击交互界面中的按钮，进行骨架页面的预览，这一过程可能会花费 20s 左右时间，当插件准备好骨架页面后，会自动通过浏览器打开预览页面，如下图。

**Comment by Hideer** [comment]
你好，我在安装的时候提示“ERROR: Failed to download Chromium r609904! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.” 你遇到了么，应该是下载chrominm需要翻墙的说法，但是翻墙还是啥无效，你有设么好的解决方法么
