### ISSUE TITLE
😄 -> "[PSG] begin to generator skeleton screen" index.bundle.js:1 😭 -> "[PSG] Cannot read property 'newPage' of null"，是什么意思，今天更新的代码

### ISSUE THREAD

**Issue by wlz1244** [ElemeFE/page-skeleton-webpack-plugin#79]
### Description

[Description of the bug or feature]

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Link to an example:** [If you're reporting a bug that's not reproducible, please try to reproduce it on [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com), [CodePen](http://codepen.io/) or a similar service and paste a link here]

### Plugin configration

for example:

```javascript
new SkeletonPlugin({
  pathname: path.resolve(__dirname, `./src`),
  port: '7890',
  loading: 'spin',
  svg: {
    color: '#EFEFEF',
    shape: 'circle',
    shapeOpposite: ['.red']
  },
  image: {
    shape: 'rect', // `rect` | `circle`
    color: '#EFEFEF',
    shapeOpposite: ['.white']
  },
  pseudo: {
    color: '#EFEFEF', // or transparent
    shape: 'circle', // circle | rect
    shapeOpposite: ['.apple', '.pen']
  },
  button: {
    color: '#EFEFEF',
    excludes: ['.center a']
  },
  defer: 5000,
  excludes: [],
  remove: [],
  hide: ['.ag-text', '.ag-image'],
  grayBlock: ['#header'],
  cssUnit: 'vw',
  cookies: [{
    name: 'SID',
    value: 'xxxxxx',
    url: 'https://xx.xxx.xx'
  }, {
    name: 'USERID',
    value: 'xxxxxx',
    url: 'https://xx.xxx.xx'
  }]
})
```

### Versions

- Page Skeleton:
- Webpack:

**Comment by wykolor** [comment]
老哥 你解决了吗 我也是这个问题

**Comment by yanzilingyan** [comment]
可以看这个链接 Mori-his 的回答
https://github.com/ElemeFE/page-skeleton-webpack-plugin/issues/105
可以解决
